#Changes in this file are not persistent.
#If you have to make changes, please edit settings.conf and run update.sh

version: "2.4"

services:

  dns:
    depends_on:
      - ipv6-nat
    build:
      context: ./container/dns
    image: server_dns:1.4
    volumes:
      - ./volumes/dns:/etc/bind
      - ./scripts:/scripts
    ports:
      - "${DNS_BINDING:-53}:53/udp"
      - "${DNS_BINDING:-53}:53/tcp"
      - "127.0.0.1:953:953/udp"
      - "127.0.0.1:953:953/tcp"
    environment:
      - SERVICE=DNS
      - ENABLED=${DNS_ENABLED:-1}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    networks:
      server:
        ipv4_address: ${NET_IPv4_PREFIX:-10.201.0}.${DNS_BRIDGE_HOST:-2}
        ipv6_address: ${NET_IPv6_PREFIX:-fd1a:2b17:1d42:cddd:}:${DNS_BRIDGE_HOST:-2}
        aliases:
          - dns

  dhcp:
    depends_on:
      - ipv6-nat
    build:
      context: ./container/dhcp
    image: server_dhcp:1.3
    volumes:
      - ./volumes/dhcp:/etc/dhcp
      - ./scripts:/scripts
    ports:
      - "${DHCP_BINDING:-67}:67/udp"
    environment:
      - SERVICE=DHCP
      - ENABLED=${DHCP_ENABLED:-1}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    networks:
      server:
        ipv4_address: ${NET_IPv4_PREFIX:-10.201.0}.${DHCP_BRIDGE_HOST:-3}
        ipv6_address: ${NET_IPv6_PREFIX:-fd1a:2b17:1d42:cddd:}:${DHCP_BRIDGE_HOST:-3}
        aliases:
          - dhcp

  freeradius:
    depends_on:
      - ipv6-nat
    build:
      context: ./container/freeradius
    image: server_freeradius:1.3
    volumes:
      - ./volumes/freeradius:/etc/freeradius/3.0
      - ./scripts:/scripts
    ports:
      - "${FREERADIUS_BINDING:-1812}:1812/udp"
    environment:
      - SERVICE=FREERADIUS
      - ENABLED=${FREERADIUS_ENABLED:-1}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    networks:
      server:
        ipv4_address: ${NET_IPv4_PREFIX:-10.201.0}.${FREERADIUS_BRIDGE_HOST:-4}
        ipv6_address: ${NET_IPv6_PREFIX:-fd1a:2b17:1d42:cddd:}:${FREERADIUS_BRIDGE_HOST:-4}
        aliases:
          - freeradius

  ipv6-nat:
    image: robbertkl/ipv6nat:latest
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:

  server:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-server
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${NET_IPv4_PREFIX:-10.201.0}.0/24
          gateway: ${NET_IPv4_PREFIX:-10.201.0}.1
        - subnet: ${NET_IPv6_PREFIX:-fd1a:2b17:1d42:cddd:}:/${NET_IPv6_NETMASK:-64}
          gateway: ${NET_IPv6_PREFIX:-fd1a:2b17:1d42:cddd:}:1
