  dhcp:
    build:
      context: ./container/dhcp
    image: server_dhcp:1.4
    volumes:
      - ./volumes/dhcp:/etc/dhcp
      - ./scripts:/scripts
    environment:
      - SERVICE=DHCP
      - ENABLED=${DHCP_ENABLED:-0}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    network_mode: host
