  dns:
    build:
      context: ./container/dns
    image: server_dns:1.6
    volumes:
      - ./volumes/dns:/etc/bind
      - ./scripts:/scripts
    environment:
      - SERVICE=DNS
      - ENABLED=${DNS_ENABLED:-0}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    network_mode: host
