  freeradius:
    depends_on:
      - ipv6-nat
    build:
      context: ./container/freeradius
    image: server_freeradius:1.3
    volumes:
      - ./volumes/freeradius:/etc/freeradius/3.0
      - ./scripts:/scripts
    ports:
      - "${FREERADIUS_BINDING:-1812}:1812/udp"
    environment:
      - SERVICE=FREERADIUS
      - ENABLED=${FREERADIUS_ENABLED:-1}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    networks:
      server:
        ipv4_address: ${NET_IPv4_PREFIX:-10.201.0}.${FREERADIUS_BRIDGE_HOST:-4}
        ipv6_address: ${NET_IPv6_PREFIX:-fd1a:2b17:1d42:cddd:}:${FREERADIUS_BRIDGE_HOST:-4}
        aliases:
          - freeradius
