  freeradius:
    build:
      context: ./container/freeradius
    image: server_freeradius:1.4
    volumes:
      - ./volumes/freeradius:/etc/freeradius/3.0
      - ./scripts:/scripts
    environment:
      - SERVICE=FREERADIUS
      - ENABLED=${FREERADIUS_ENABLED:-0}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    network_mode: host
