  ejabberd:
    build:
      context: ./container/ejabberd
    image: server_ejabberd:1.1
    volumes:
      - ./volumes/ejabberd:/etc/ejabberd
      - ./scripts:/scripts
    ports:
      - "5222:5222/tcp"
      - "5223:5223/tcp"
      - "5269:5269/tcp"
      - "5280:5280/tcp"
    environment:
      - SERVICE=EJABBERD
      - ENABLED=${EJABBERD_ENABLED:-0}
      - TIMEZONE=${TIMEZONE:-UTC}
    restart: always
    networks:
      server:
        ipv4_address: ${NET_IPv4_PREFIX:-10.201.0}.${EJABBERD_BRIDGE_HOST:-5}
        ipv6_address: ${NET_IPv6_PREFIX:-fd1a:2b17:1d42:cddd:}:${EJABBERD_BRIDGE_HOST:-5}
        aliases:
          - ejabberd
